name: Run integration tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.0]
        laravel: [8]
        stability: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Create test database
        run: |
          sudo systemctl start mysql.service
          mysqladmin create aina --user="root" --password="root"

      - name: Create project
        run: |
          composer create-project --prefer-dist laravel/laravel:^${{ matrix.laravel }} tests/integration --no-interaction

      - name: Determine Hearth version
        run: |
          echo "hearth_version=${{ github.head_ref }}" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      - name: Determine Hearth version
        run: |
          echo "hearth_version=main" >> $GITHUB_ENV
        if: github.event_name != 'pull_request'

      - name: Install hearth
        run: |
          cd tests/integration
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
          composer require fluid-project/hearth:dev-${{ env.hearth_version }} --with-all-dependencies --no-interaction
          php artisan hearth:install --two-factor

      - name: Run tests
        env:
          DB_PASSWORD: root
          DB_HOST: localhost
        run: |
          php artisan migrate
          vendor/bin/phpunit
